execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:dirt",Count:1b,tag:{dirt:1}},{Slot:4b,id:"minecraft:oak_leaves",Count:1b,tag:{leaves:1}},{Slot:1b,id:"minecraft:dirt",Count:1b,tag:{dirt:1}},{Slot:2b,id:"minecraft:dirt",Count:1b,tag:{dirt:1}},{Slot:3b,id:"minecraft:dirt",Count:1b,tag:{dirt:1}},{Slot:5b,id:"minecraft:dirt",Count:1b,tag:{dirt:1}},{Slot:6b,id:"minecraft:dirt",Count:1b,tag:{dirt:1}},{Slot:7b,id:"minecraft:dirt",Count:1b,tag:{dirt:1}},{Slot:8b,id:"minecraft:dirt",Count:1b,tag:{dirt:1}}]} run function opdirt:craftingresults/leaves/leavesvanilla

execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:oak_leaves",Count:1b,tag:{leaves:1}},{Slot:1b,id:"minecraft:oak_leaves",Count:1b,tag:{leaves:1}},{Slot:2b,id:"minecraft:oak_leaves",Count:1b,tag:{leaves:1}},{Slot:3b,id:"minecraft:oak_leaves",Count:1b,tag:{leaves:1}},{Slot:5b,id:"minecraft:oak_leaves",Count:1b,tag:{leaves:1}},{Slot:6b,id:"minecraft:oak_leaves",Count:1b,tag:{leaves:1}},{Slot:7b,id:"minecraft:oak_leaves",Count:1b,tag:{leaves:1}},{Slot:8b,id:"minecraft:oak_leaves",Count:1b,tag:{leaves:1}},{Slot:4b,id:"minecraft:bucket",Count:1b}]} run function opdirt:craftingresults/begginerstuff/water_bucket

# Leaves stack
execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:oak_leaves",Count:64b},{Slot:1b,id:"minecraft:oak_leaves",Count:64b},{Slot:2b,id:"minecraft:oak_leaves",Count:64b},{Slot:3b,id:"minecraft:oak_leaves",Count:64b},{Slot:4b,id:"minecraft:oak_leaves",Count:64b},{Slot:5b,id:"minecraft:oak_leaves",Count:64b},{Slot:6b,id:"minecraft:oak_leaves", Count:64b},{Slot:7b,id:"minecraft:oak_leaves",Count:64b},{Slot:8b,id:"minecraft:oak_leaves",Count:64b}]} run function opdirt:craftingresults/leaves/leaves_stack

execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:spruce_leaves",Count:64b},{Slot:1b,id:"minecraft:spruce_leaves",Count:64b},{Slot:2b,id:"minecraft:spruce_leaves",Count:64b},{Slot:3b,id:"minecraft:spruce_leaves",Count:64b},{Slot:4b,id:"minecraft:spruce_leaves",Count:64b},{Slot:5b,id:"minecraft:spruce_leaves",Count:64b},{Slot:6b,id:"minecraft:spruce_leaves", Count:64b},{Slot:7b,id:"minecraft:spruce_leaves",Count:64b},{Slot:8b,id:"minecraft:spruce_leaves",Count:64b}]} run function opdirt:craftingresults/leaves/leaves_stack

function opdirt:craftingresults/leaves/leaves