execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:4b,id:"minecraft:oak_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla1
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:15}},{Slot:4b,id:"minecraft:oak_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla2
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:30}},{Slot:4b,id:"minecraft:oak_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla3
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:45}},{Slot:4b,id:"minecraft:oak_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla4

execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:4b,id:"minecraft:spruce_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla1
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:15}},{Slot:4b,id:"minecraft:spruce_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla2
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:30}},{Slot:4b,id:"minecraft:spruce_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla3
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:45}},{Slot:4b,id:"minecraft:spruce_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla4

execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:4b,id:"minecraft:jungle_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla1
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:15}},{Slot:4b,id:"minecraft:jungle_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla2
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:30}},{Slot:4b,id:"minecraft:jungle_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla3
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:45}},{Slot:4b,id:"minecraft:jungle_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla4

execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:4b,id:"minecraft:birch_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla1
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:15}},{Slot:4b,id:"minecraft:birch_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla2
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:30}},{Slot:4b,id:"minecraft:birch_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla3
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:45}},{Slot:4b,id:"minecraft:birch_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla4

execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:4b,id:"minecraft:dark_oak_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla1
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:15}},{Slot:4b,id:"minecraft:dark_oak_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla2
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:30}},{Slot:4b,id:"minecraft:dark_oak_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla3
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:45}},{Slot:4b,id:"minecraft:dark_oak_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla4

execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:4b,id:"minecraft:acacia_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla1
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:15}},{Slot:4b,id:"minecraft:acacia_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla2
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:30}},{Slot:4b,id:"minecraft:acacia_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla3
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:45}},{Slot:4b,id:"minecraft:acacia_leaves",Count:1b}]} run function opdirt:craftingresults/string/stringvanilla4

function opdirt:craftingresults/string/string1

#String2
execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:4b,id:"minecraft:oak_leaves",Count:32b},{Slot:0b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:1b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:2b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:3b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:5b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:6b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:8b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}}]} run function opdirt:craftingresults/string/string2

execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:4b,id:"minecraft:spruce_leaves",Count:32b},{Slot:0b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:1b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:2b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:3b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:5b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:6b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:8b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}}]} run function opdirt:craftingresults/string/string2

execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:4b,id:"minecraft:birch_leaves",Count:32b},{Slot:0b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:1b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:2b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:3b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:5b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:6b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:8b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}}]} run function opdirt:craftingresults/string/string2

execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:4b,id:"minecraft:acacia_leaves",Count:32b},{Slot:0b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:1b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:2b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:3b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:5b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:6b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:8b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}}]} run function opdirt:craftingresults/string/string2

execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:4b,id:"minecraft:dark_oak_leaves",Count:32b},{Slot:0b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:1b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:2b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:3b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:5b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:6b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:8b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}}]} run function opdirt:craftingresults/string/string2

execute if block ~ ~ ~ dropper{Items:[{Slot:7b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:4b,id:"minecraft:jungle_leaves",Count:32b},{Slot:0b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:1b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:2b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:3b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:5b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:6b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}},{Slot:8b,id:"minecraft:wooden_hoe",Count:1b,tag:{crook:1,Damage:0}}]} run function opdirt:craftingresults/string/string2