execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:oak_leaves",Count:1b},{Slot:1b,id:"minecraft:oak_leaves",Count:1b},{Slot:2b,id:"minecraft:oak_leaves",Count:1b},{Slot:3b,id:"minecraft:oak_leaves",Count:1b},{Slot:4b,id:"minecraft:oak_leaves",Count:1b},{Slot:5b,id:"minecraft:oak_leaves",Count:1b},{Slot:6b,id:"minecraft:oak_leaves", Count:1b},{Slot:7b,id:"minecraft:oak_leaves",Count:1b},{Slot:8b,id:"minecraft:oak_leaves",Count:1b}]} run function opdirt:craftingresults/leaves/enchanted_leaves

execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:spruce_leaves",Count:1b},{Slot:1b,id:"minecraft:spruce_leaves",Count:1b},{Slot:2b,id:"minecraft:spruce_leaves",Count:1b},{Slot:3b,id:"minecraft:spruce_leaves",Count:1b},{Slot:4b,id:"minecraft:spruce_leaves",Count:1b},{Slot:5b,id:"minecraft:spruce_leaves",Count:1b},{Slot:6b,id:"minecraft:spruce_leaves", Count:1b},{Slot:7b,id:"minecraft:spruce_leaves",Count:1b},{Slot:8b,id:"minecraft:spruce_leaves",Count:1b}]} run function opdirt:craftingresults/leaves/enchanted_leaves

execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:birch_leaves",Count:1b},{Slot:1b,id:"minecraft:birch_leaves",Count:1b},{Slot:2b,id:"minecraft:birch_leaves",Count:1b},{Slot:3b,id:"minecraft:birch_leaves",Count:1b},{Slot:4b,id:"minecraft:birch_leaves",Count:1b},{Slot:5b,id:"minecraft:birch_leaves",Count:1b},{Slot:6b,id:"minecraft:birch_leaves", Count:1b},{Slot:7b,id:"minecraft:birch_leaves",Count:1b},{Slot:8b,id:"minecraft:birch_leaves",Count:1b}]} run function opdirt:craftingresults/leaves/enchanted_leaves

execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:jungle_leaves",Count:1b},{Slot:1b,id:"minecraft:jungle_leaves",Count:1b},{Slot:2b,id:"minecraft:jungle_leaves",Count:1b},{Slot:3b,id:"minecraft:jungle_leaves",Count:1b},{Slot:4b,id:"minecraft:jungle_leaves",Count:1b},{Slot:5b,id:"minecraft:jungle_leaves",Count:1b},{Slot:6b,id:"minecraft:jungle_leaves", Count:1b},{Slot:7b,id:"minecraft:jungle_leaves",Count:1b},{Slot:8b,id:"minecraft:jungle_leaves",Count:1b}]} run function opdirt:craftingresults/leaves/enchanted_leaves

execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:acacia_leaves",Count:1b},{Slot:1b,id:"minecraft:acacia_leaves",Count:1b},{Slot:2b,id:"minecraft:acacia_leaves",Count:1b},{Slot:3b,id:"minecraft:acacia_leaves",Count:1b},{Slot:4b,id:"minecraft:acacia_leaves",Count:1b},{Slot:5b,id:"minecraft:acacia_leaves",Count:1b},{Slot:6b,id:"minecraft:acacia_leaves", Count:1b},{Slot:7b,id:"minecraft:acacia_leaves",Count:1b},{Slot:8b,id:"minecraft:acacia_leaves",Count:1b}]} run function opdirt:craftingresults/leaves/enchanted_leaves

execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:dark_oak_leaves",Count:1b},{Slot:1b,id:"minecraft:dark_oak_leaves",Count:1b},{Slot:2b,id:"minecraft:dark_oak_leaves",Count:1b},{Slot:3b,id:"minecraft:dark_oak_leaves",Count:1b},{Slot:4b,id:"minecraft:dark_oak_leaves",Count:1b},{Slot:5b,id:"minecraft:dark_oak_leaves",Count:1b},{Slot:6b,id:"minecraft:dark_oak_leaves", Count:1b},{Slot:7b,id:"minecraft:dark_oak_leaves",Count:1b},{Slot:8b,id:"minecraft:dark_oak_leaves",Count:1b}]} run function opdirt:craftingresults/leaves/enchanted_leaves