execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:netherite_block",Count:1b,tag:{display:{Name:'{"text":"Super Netherite Block","color":"#5C2501","bold":true,"italic":false}'}}},{Slot:2b,id:"minecraft:netherite_block",Count:1b,tag:{display:{Name:'{"text":"Super Netherite Block","color":"#5C2501","bold":true,"italic":false}'},Enchantments:[{}]}},{Slot:3b,id:"minecraft:netherite_block",Count:1b,tag:{display:{Name:'{"text":"Super Netherite Block","color":"#5C2501","bold":true,"italic":false}'},Enchantments:[{}]}},{Slot:4b,id:"minecraft:netherite_block",Count:1b,tag:{display:{Name:'{"text":"Super Netherite Block","color":"#5C2501","bold":true,"italic":false}'},Enchantments:[{}]}},{Slot:5b,id:"minecraft:netherite_block",Count:1b,tag:{display:{Name:'{"text":"Super Netherite Block","color":"#5C2501","bold":true,"italic":false}'},Enchantments:[{}]}},{Slot:6b,id:"minecraft:netherite_block",Count:1b,tag:{display:{Name:'{"text":"Super Netherite Block","color":"#5C2501","bold":true,"italic":false}'},Enchantments:[{}]}},{Slot:7b,id:"minecraft:netherite_block",Count:1b,tag:{display:{Name:'{"text":"Super Netherite Block","color":"#5C2501","bold":true,"italic":false}'},Enchantments:[{}]}},{Slot:8b,id:"minecraft:netherite_block",Count:1b,tag:{display:{Name:'{"text":"Super Netherite Block","color":"#5C2501","bold":true,"italic":false}'},Enchantments:[{}]}}]} run function opdirt:craftingresults/opstuff/strongheavyarmor

execute if block ~ ~ ~ dropper{Items:[{Slot:4b,id:"minecraft:oak_log",Count:1b,tag:{log:2}},{Slot:7b,id:"minecraft:oak_log",Count:1b,tag:{log:2}}]} run function opdirt:craftingresults/wood/stick

execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:7b,id:"minecraft:stick",Count:1b,tag:{tag:{stick:1}}},{Slot:1b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:2b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:4b,id:"minecraft:stick",Count:1b,tag:{tag:{stick:1}}}]} run function opdirt:craftingresults/opstuff/perfect_pickaxe

execute if block ~ ~ ~ dropper{Items:[{Slot:4b,id:"minecraft:netherite_block",Count:4b,tag:{netherite:4}}]} run function opdirt:craftingresults/endgamestuff/bedrock

execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:3b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:4b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:5b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:6b,id:"minecraft:netherite_block", Count:1b,tag:{netherite:4}},{Slot:7b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:8b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}}]} run function opdirt:craftingresults/opstuff/strongheavyarmor

execute if block ~ ~ ~ dropper{Items:[{Slot:3b,id:"minecraft:iron_ingot",Count:1b,tag:{tag:{iron_ingot:1}}},{Slot:6b,id:"minecraft:iron_block",Count:1b,tag:{tag:{iron_block:1}}},{Slot:5b,id:"minecraft:iron_ingot",Count:1b,tag:{tag:{iron_ingot:1}}},{Slot:8b,id:"minecraft:iron_block",Count:1b,tag:{tag:{iron_block:1}}}]} run function opdirt:craftingresults/opstuff/speed_boots

execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:magma_block",Count:1b,tag:{hot:3}},{Slot:1b,id:"minecraft:magma_block",Count:1b,tag:{hot:3}},{Slot:2b,id:"minecraft:magma_block",Count:1b,tag:{hot:3}},{Slot:3b,id:"minecraft:magma_block",Count:1b,tag:{hot:3}},{Slot:5b,id:"minecraft:magma_block",Count:1b,tag:{hot:3}},{Slot:6b,id:"minecraft:magma_block", Count:1b,tag:{hot:3}},{Slot:8b,id:"minecraft:magma_block",Count:1b,tag:{hot:3}}]} run function opdirt:craftingresults/opstuff/magma_pants

execute if block ~ ~ ~ dropper{Items:[{Slot:4b,id:"minecraft:magma_block",Count:1b,tag:{hot:3}},{Slot:7b,id:"minecraft:magma_block",Count:1b,tag:{hot:3}}]} run function opdirt:craftingresults/opstuff/flaming_rod

execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:1b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:2b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:3b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:4b,id:"minecraft:elytra",Count:1b,tag:{tag:{chorus:4}}},{Slot:5b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:6b,id:"minecraft:netherite_block", Count:1b,tag:{netherite:4}},{Slot:7b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}},{Slot:8b,id:"minecraft:netherite_block",Count:1b,tag:{netherite:4}}]} run function opdirt:craftingresults/chorus/opwings

execute if block ~ ~ ~ dropper{Items:[{Slot:4b,id:"minecraft:dirt",Count:1b}]} run function opdirt:craftingresults/endgamestuff/fireworks

execute if block ~ ~ ~ dropper{Items:[{Slot:1b,id:"minecraft:purpur_block",Count:1b,tag:{tag:{chorus:3}}},{Slot:4b,id:"minecraft:purpur_block",Count:1b,tag:{tag:{chorus:3}}},{Slot:7b,id:"minecraft:purpur_block",Count:1b,tag:{tag:{chorus:3}}}]} run function opdirt:craftingresults/chorus/flying_rod

execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:cooked_porkchop"},{Slot:1b,id:"minecraft:cooked_porkchop"},{Slot:2b,id:"minecraft:cooked_porkchop"},{Slot:3b,id:"minecraft:cooked_porkchop"},{Slot:4b,id:"minecraft:furnace",Count:1b,tag:{cobble:4}},{Slot:5b,id:"minecraft:cooked_porkchop"},{Slot:6b,id:"minecraft:cooked_porkchop"},{Slot:7b,id:"minecraft:magma_block",Count:1b,tag:{hot:3}},{Slot:8b,id:"minecraft:cooked_porkchop"}]} run function opdirt:craftingresults/opstuff/super_bacon

execute if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:gold_block",Count:1b,tag:{gold:2}},{Slot:1b,id:"minecraft:diamond_block",Count:1b,tag:{diamond:1}},{Slot:2b,id:"minecraft:gold_block",Count:1b,tag:{gold:2}},{Slot:3b,id:"minecraft:gold_block",Count:1b,tag:{gold:2}},{Slot:5b,id:"minecraft:gold_block",Count:1b,tag:{gold:2}}]} run function opdirt:craftingresults/opstuff/crown